### ISSUE TITLE
Tell us more!

### ISSUE THREAD

**Issue by dguerri** [wolfSSL/wolfTPM#1]
What's up with this repo? I am super curious :D

**Comment by kaleb-himes** [comment]
Hi Dguerri,

Would you mind opening a ticket at support@wolfssl.zendesk.com or sending an email to support@wolfssl.com for inquiry tracking?

Once I receive a support ticket from you I'll assign it to David Garske, our engineer doing the work on TPM 2.0 support, and ask him to send you an update on this repo.

Thanks!

- Kaleb
