### ISSUE TITLE
wolftpm C# wrapper needs to implement IDisposable instead of using Finalizer.

### ISSUE THREAD

**Issue by zhichao-h** [wolfSSL/wolfTPM#221]
In the wolfTPM.cs, when cleaning up resources, the C# Finalizer are used instead of following the IDisposable. This can be dangerous as the resources are only cleaned up when the finalizers are run by the GC (hopefully). In many cases, the finalizer may never run as such resource leak will ensure.

The following classes should implement IDisposable:

- KeyBlob
- Key
- Template
- Session
- Device.

**Comment by dgarske** [comment]
Hi @zhichao-h , great suggestion! I will get a PR put up tomorrow fixing the way the classes are finalized.

**Comment by dgarske** [comment]
Fixed in #225. Marking closed.
