### ISSUE TITLE
Support for  SLB 9645SLB ? (I2C)

### ISSUE THREAD

**Issue by mypiandrew** [wolfSSL/wolfTPM#57]
Hi

Does this work for the Infineon SLB9645 I2C TPM?

https://www.rutronik24.com/search-result/qs:SLB9645/reset:0

www.infineon.com/dgdl/Infineon-+SLB+9645_SLB+9670+TPM+1.2+-AN-v06_16-EN.zip?fileId=5546d46255a50e820155b535d44d754f

**Comment by dgarske** [comment]
Hi Andrew,

Thanks for your question (and support ticket). For I2C we currently only support the STM ST33TPHF20I2C or ST33TPHF2EI2C parts with the TPM 2.0 specification.

The SLB 9645 part is using the TPM v1.2 specification, which is currently not compatible with wolfTPM as it is designed with TPM v2.0 support.

We could possibly add support and will continue dialog via support discussion.

Thanks,
David Garske, wolfSSL
